### ISSUE TITLE
Check if version bump is possible

### ISSUE THREAD

**Issue by marden35** [sky-uk/what-bump#19]
I'd like what-bump to expose a new "standalone" functionality: check the correctness of a series of commits.

This would be really useful before trying to bump. For example:
- a PR is reviewed and approved
- the opener squashes and merges the PR
- what-bump check if the comment is conventional-commits compliant
- do the bump

So the idea is to use it as hook in PR flow.

**Comment by albx79** [comment]
This is already possible by issuing `what-bump HEAD^ --strict`, which will return a non-zero exit code if the commit message is non-compliant.
